mqtt:
  broker: "broker.hivemq.com"
  port: 1883
  base_topic: "02269_pm_group9/#"
miner:
  address: "http://localhost:8001"
log:
  file: "../log/app.log"
  level: 20
  format: "%(levelname).8s %(asctime)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"